# Generated by Django 5.0.1 on 2024-02-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=150)),
                ('ome_of_visit', models.DateTimeField(auto_now=True)),
                ('purchases', models.TextField()),
            ],
        ),
    ]
