# Generated by Django 5.0.1 on 2024-02-06 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_visitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='size',
        ),
    ]
